### ISSUE TITLE
作者这个可以进行二次开发吗，表明原作者与改编，只用于自己服务器，不商用不卖钱

### ISSUE THREAD

**Issue by guogai114514** [PowerKG/HyperStamina#1]

**Comment by PowerKG** [comment]
欢迎二次开发与分享，不过这个是五年前的作品了，应该存在蛮多的问题，我也不记得当时写得如何了。欢迎关注我的新GitHub账号https://github.com/HyrKG

**Comment by guogai114514** [comment]
大佬可以加下QQ好友吗，怕有问题找不到您了

**Comment by guogai114514** [comment]
大佬，这个idea使用gbk作为项目编码，然后放在服务端内，报错

**Comment by guogai114514** [comment]
[20:10:57 ERROR]: Could not load 'plugins\Hyper-RC.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 1, column 1:
    name: RC-Hyper
    ^
expected <block end>, but found Scalar
 in 'reader', line 5, column 22:
    description: [ 鏀圭紪鐗?] 浣撳姏鎻掍欢鐢盧C杩涜浜屾寮€鍙??
                         ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:571) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:452) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:228) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:157) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]

**Comment by guogai114514** [comment]
这个要是换utf-8进行打包，utf就没法解码中文字符了

**Comment by guogai114514** [comment]
作者我V你15可以帮我解决问题吗
